# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eaca0ccfd74444b9f79cd7c0cc8e87be"
name = "Revenue Boost"
application_url = "https://revenue-boost.app/app"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts,write_products,read_themes"
optional_scopes = [
  "read_customers",
  "write_customers",
  "write_files",
  "write_marketing_events",
  "read_marketing_events",
  "read_orders"
]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://revenue-boost.app/auth/callback",
  "https://revenue-boost.app/auth/shopify/callback",
  "https://revenue-boost.app/api/auth/callback"
]

[app_proxy]
url = "https://revenue-boost.app"
subpath = "revenue-boost"
prefix = "apps"
[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
